# DataPacksJob.yaml
projectPath: ./VlocityCard
expansionPath: ./VlocityCard/VlocityCard/test2/VlocityCard/test2/VlocityCard/datadeploy
defaultJob: Deploy
jobs:
  Deploy:
    preJobApex:
    postJobApex:
    postDeployApex:
    queries:
    - VlocityUITemplate
    - VlocityCard
    - VlocityAction
    - VlocityIntegrationProcedure
    - VlocityDataRaptor
    - VlocityOmniScript
