# DataPacksJob.yaml
projectPath: ./VlocityCard
defaultJob: Deploy
jobs:
  Deploy:
    preJobApex:
    postJobApex:
    postDeployApex:
    queries:
    - VlocityCard:
          # You can specify the specific card by its name or other criteria
          VlocityMatchingKey: Name
          Name: testdatadeploy
    #- VlocityUITemplate
    #- VlocityCard
    #- VlocityAction
    #- VlocityIntegrationProcedure
    #- VlocityDataRaptor
    #- VlocityOmniScript
