projectPath: ./VlocityCard
expansionPath: "./VlocityCard/VlocityCard/test2/VlocityCard/test2/VlocityCard/datadeploy"
queries: 
  - VlocityDataPackType: SObject
    query: "SELECT Id FROM %vlocity_namespace%__VlocityCard__c WHERE %vlocity_namespace%__GlobalKey__c = 'datadeploy/data_deploy/1/1714593473963' LIMIT 1"
