name: Salesforce CICD

on:
  push:
    branches:
      - main

jobs:
  Authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Salesforce CLI
        run: |
          npm install -g sfdx-cli --global
    
      - name: Install Vlocity Build Tool
        run: npm install -g vlocity
    
      - name: Use SOAP API for Deployment
        run: |
          sfdx config:set restDeploy=false --global

      - name: Authorize Salesforce DeployTestOrg Org
        run: |
         sfdx force:auth:jwt:grant --clientid 3MVG9NYvTkhtdEI5Z9dZmBB.toZ_f9ZTkCtyPmQsts6QEJINuMe.ywRNgQcUztn1n6Aw8r8OZ0uJHhAIos7nX --jwtkeyfile mycerts/server.key --username bxkumar1@sentara.com.cicd2 --instanceurl https://sentarahealth--cicd2.sandbox.my.salesforce.com 
    
      - name: Verify Salesforce Connection
        id: verify_connection
        run: |
          sfdx force:org:display -u bxkumar1@sentara.com.cicd2

      - name: Deploy source code to DeployTestOrg Org
        run: |
         sfdx force:source:deploy -p force-app -w 10 -u bxkumar1@sentara.com.cicd2
    
      - name: Import Data to Org B
        run: vlocity -job .github/workflows/DataPacksJob.yaml -sfdx.username bxkumar1@sentara.com.cicd2

      #- name: Update the Project from source
       # run: |
        # vlocity packUpdateSettings -projectPath ./VlocityCard -sfdx.username bxkumar1@sentara.com.cicd2

     # - name: Deploy Vlocity Components using Manifest
      #  run: |
       #   vlocity packExport -sfdx.username bxkumar1@sentara.com.cicd2 -job .github/workflows/DataPacksJob.yaml

     # - name: Deploy DataPack
        #run: vlocity -propertyfile .github/workflows/DataPacksJob.yaml packDeploy -job deploy

      - name: Deploy Vlocity Components using Manifest
        run: |
          vlocity packDeploy -job .github/workflows/DataPacksJob.yaml -sfdx.username bxkumar1@sentara.com.cicd2


